//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DetalleMascotas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pet
    {
        public int PetId { get; set; }
        public string PetName { get; set; }
        public Nullable<int> age { get; set; }
        public string color { get; set; }
        public Nullable<int> OwnerId { get; set; }
    
        public virtual Owner Owner { get; set; }
    }
}
